name: ip
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - expat=2.7.3=h3385a95_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libnsl=2.0.0=h5eee18b_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.18=hd6dcaed_0
  - pip=25.3=pyh8b19718_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.12.12=hd17a9e1_1
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=pyhff2d567_0
  - sqlite=3.51.0=h2a70700_0
  - tk=8.6.15=h54e0aa7_0
  - tzdata=2025b=h78e105d_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - aniso8601==10.0.1
      - attrs==25.4.0
      - blinker==1.9.0
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - cryptography==46.0.3
      - dashscope==1.25.1
      - flask==3.1.2
      - flask-restx==1.3.2
      - frozenlist==1.8.0
      - idna==3.11
      - importlib-resources==6.5.2
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - jsonschema==4.17.3
      - libclang==18.1.1
      - markupsafe==3.0.3
      - multidict==6.7.0
      - propcache==0.4.1
      - pycparser==2.23
      - pyrsistent==0.20.0
      - referencing==0.23.0
      - requests==2.32.5
      - tree-sitter==0.25.0
      - tree-sitter-c==0.24.1
      - typing-extensions==4.15.0
      - urllib3==2.5.0
      - websocket-client==1.9.0
      - werkzeug==3.1.4
      - wllvm==1.3.1
      - yarl==1.22.0
prefix: /root/miniconda3/envs/ip
